spring:
  datasource:
    url: jdbc:h2:mem:credit_system_db
    username: sa
    #password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      properties:
        hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false